[en]
  title = "ğŸ‘ŒTeletubby's Blog"
  languageName = "English"
  weight = 1
  languagedir = "ltr"
  contentdir = "content/en"

[zh]
  title = "ğŸ‘Œå¤©çº¿å®å®çš„åšå®¢"
  languageName = "ç®€ä½“ä¸­æ–‡"
  weight = 2
  languagedir = "ltr"
  contentdir = "content/zh"