logoText = "Teletubby"
logoType = "short" # long, short
logo = true
description = "SUP?"
custom_css = []
custom_js = []
useFaviconGenerator = true # https://www.favicon-generator.org/
languagedir = "ltr"
meta_image = ""
themecolor = ""

themeOptions = ["dark", "light", "hacker", "solarized", "kimbie"]
notAllowedTypesInHome = ["contact", "talks", "about", "showcase", "publication", "presentation", "resume"]
notAllowedTypesInHomeSidebar = ["about", "archive", "showcase", "publication", "presentation", "resume"]
notAllowedTypesInArchive = ["about", "talks", "showcase", "publication", "presentation", "resume"]
notAllowedTypesInHomeFeed = ["about", "archive", "contact", "talks", "showcase", "publication", "presentation", "resume", "gallery"]

enableUiAnimation = true
hideSingleContentsWhenJSDisabled = false

# header
homeHeaderType = "text" # text, img, slide

# menu
showMobileMenuTerms = ["tags", "categories", "series"]

# body
enableBreadcrumb = true
enablePhotoSwipe = true
enableSearch = true
enableSearchHighlight = true
enableGoToTop = true
enableWhoami = true
summaryShape = "classic" # card, classic, compact
searchResultPosition = "main" # side, main
archiveGroupByDate = "2006" # "2006-01": group by month, "2006": group by year
archivePaginate = 13
paginateWindow = 1
talksPaginate = 5
talksGroupByDate = "2006"
pubPaginate = 20

# whoami
myname = "Teletubby"
email = "oops!@gmail.com"
whoami = "å¼ƒæˆ‘å»è€…æ˜¨æ—¥ä¹‹æ—¥ä¸å¯ç•™ï¼Œä¹±æˆ‘å¿ƒè€…ä»Šæ—¥ä¹‹æ—¥å¤šçƒ¦å¿§"
bioImageUrl = ""
useGravatar = false
location = "Changsha, China"
organization = "æ‡’äººğŸ¤“å¤œçŒ«å­"
#link = "https://zzossig.io/ko"

# sidebar
enableBio = true
enableBioImage = true
enableSidebar = true
enableSidebarTags = true
enableSidebarSeries = true
enableSidebarCategories = true
enableHomeSidebarTitles = true
enableListSidebarTitles = true
enableToc = true
hideToc = false
tocFolding = true
tocPosition = "inner" # inner, outer
enableTocSwitch = true
itemsPerCategory = 5
sidebarPosition = "right"
tocLevels = ["h2", "h3", "h4"]
enableSidebarPostsByOrder = false

# footer
showPoweredBy = false
showFeedLinks = true
showSocialLinks = true
enableLangChange = true
enableThemeChange = true

# service
googleTagManager = "" # GTM-XXXXXX
baiduAnalytics = ""
enableBusuanzi = false
busuanziSiteUV = true
busuanziSitePV = true
busuanziPagePV = true

# comment
enableComment = true
disqus_shortname = "" 
commento = false

[gitment]          	# Gitment is a comment system based on GitHub issues. see https://github.com/imsun/gitment
owner = ""              	# Your GitHub ID
repo = ""               	# The repo to store comments
clientId = ""           	# Your client ID
clientSecret = ""      	# Your client secret

[utterances]       	# https://utteranc.es/
owner = ""              	# Your GitHub ID
repo = ""               	# The repo to store comments

[gitalk]           	# Gitalk is a comment system based on GitHub issues. see https://github.com/gitalk/gitalk
owner = ""              	# Your GitHub ID
repo = ""               	# The repo to store comments
clientId = ""           	# Your client ID
clientSecret = ""      	# Your client secret

# rss
updatePeriod = "" # Possible values: 'hourly', 'daily', 'weekly', 'monthly', or 'yearly'.
updateFrequency = ""
fullContents = false

# comment
enableComment = true
disqus_shortname = ""
commento = false

[telegram]
  enable = false
  siteId = ""
  dataLimit = 5

# Valine.
# You can get your appid and appkey from https://leancloud.cn
# more info please open https://valine.js.org
[valine]
  enable = false
  appId = 'ä½ çš„appId'
  appKey = 'ä½ çš„appKey'
  notify = false  	# mail notifier , https://github.com/xCss/Valine/wiki
  verify = false 	# Verification code
  avatar = 'mm' 
  placeholder = 'è¯´ç‚¹ä»€ä¹ˆå§...'
  visitor = false

[changyan]
  changyanAppid = ""        	# Changyan app id             	# ç•…è¨€
  changyanAppkey = ""       	# Changyan app key

[livere]
  livereUID = ""            	# LiveRe UID                  	# æ¥å¿…åŠ›

# Isso: https://posativ.org/isso/
[isso]
  enable = false
  scriptSrc = "" # "https://isso.example.com/js/embed.min.js"
  dataAttrs = "" # "data-isso='https://isso.example.com' data-isso-require-author='true'"

[socialOptions]
  email = "mailto:lt1339264174@163.com"
  phone = ""
  facebook = ""
  twitter = ""
  github = "https://github.com/iiiJESUSiii"
  stack-overflow = ""
  instagram = ""
  google-plus = ""
  youtube = ""
  medium = ""
  tumblr = ""
  linkedin = ""
  pinterest = ""
  stack-exchange = ""
  telegram = ""
  steam = "https://steamcommunity.com/profiles/76561199005943110/"
  weibo = ""
  douban = ""
  csdn = ""
  gitlab = ""
  mastodon = ""
  jianshu = ""
  zhihu = "https://www.zhihu.com/people/ha-tao-46"
  signal = ""
  whatsapp = ""
  matrix = ""
  xmpp = ""
  dev-to = ""
  gitea = ""
  google-scholar = ""

[donationOptions]
  enable = false 	# if set, the donation button will show up on the single page.
  alipay = "" 	# Alipay QR Code image (example path: images/donation/alipay-qrcode.png) and put   your file at root/static/images/donation/
  wechat = "" 	# Wechat pay QR Code image (example path: same as above)
  paypal = "" 	# Paypal URL
  patreon = "" 	# Patreon URL

[copyrightOptions]
  enableCopyrightLink = false # if set, you can add copyright link
  copyrightLink = ""
  copyrightLinkImage = ""
  copyrightLinkText = ""

# possible share name: ["facebook","twitter", "reddit", "linkedin", "tumblr", "weibo", "douban", "line"]
[[share]]
  name = "facebook"
  username = ""
[[share]]
  name = "twitter"

[[footerLinks]]
  name = ""
  link = ""
[[footerLinks]]
  name = ""
  link = ""